export type PermissionDef = {
  code: string;
  module: string;
  description?: string;
};

export const PERMISSIONS: PermissionDef[] = [
  { code: "dashboard.view", module: "dashboard", description: "View role dashboard" },

  { code: "student.view", module: "student", description: "View student records" },
  { code: "student.create", module: "student", description: "Create students" },
  { code: "student.edit", module: "student", description: "Edit student records" },
  { code: "student.archive", module: "student", description: "Archive/withdraw students" },
  { code: "student.profile.self", module: "student", description: "Access own student profile" },

  { code: "faculty.view", module: "faculty", description: "View faculty records" },
  { code: "faculty.create", module: "faculty", description: "Create faculty" },
  { code: "faculty.edit", module: "faculty", description: "Edit faculty records" },

  { code: "department.view", module: "department", description: "View department data" },
  { code: "department.create", module: "department", description: "Create departments" },
  { code: "department.edit", module: "department", description: "Edit departments" },
  { code: "department.assign_hod", module: "department", description: "Assign HOD / coordinators" },

  { code: "academic.view", module: "academic", description: "View academic configuration" },
  { code: "academic.configure", module: "academic", description: "Configure schemes/programs/semesters" },

  { code: "course.view", module: "course", description: "View courses" },
  { code: "course.create", module: "course", description: "Create courses" },
  { code: "course.edit", module: "course", description: "Edit courses" },
  { code: "course.assign", module: "course", description: "Assign faculty to courses" },
  { code: "course.register", module: "course", description: "Manage course registration" },

  { code: "attendance.view", module: "attendance", description: "View attendance" },
  { code: "attendance.create", module: "attendance", description: "Mark attendance" },
  { code: "attendance.edit", module: "attendance", description: "Edit attendance" },
  { code: "attendance.approve", module: "attendance", description: "Approve/override attendance" },

  { code: "timetable.view", module: "timetable", description: "View timetable" },
  { code: "timetable.create", module: "timetable", description: "Create timetable entries" },
  { code: "timetable.edit", module: "timetable", description: "Edit timetable" },

  { code: "assessment.view", module: "assessment", description: "View internal assessments" },
  { code: "assessment.create", module: "assessment", description: "Create assessments" },
  { code: "assessment.edit", module: "assessment", description: "Edit assessments" },
  { code: "assessment.publish", module: "assessment", description: "Publish assessments" },

  { code: "questionbank.view", module: "questionbank", description: "View question bank" },
  { code: "questionbank.create", module: "questionbank", description: "Add questions" },
  { code: "questionbank.edit", module: "questionbank", description: "Edit questions" },
  { code: "questionbank.approve", module: "questionbank", description: "Approve questions" },

  { code: "questionpaper.create", module: "questionpaper", description: "Create question papers" },
  { code: "questionpaper.submit", module: "questionpaper", description: "Submit for approval" },
  { code: "questionpaper.approve", module: "questionpaper", description: "Approve question papers" },

  { code: "ciemarks.enter", module: "cie", description: "Enter CIE marks" },
  { code: "ciemarks.view", module: "cie", description: "View CIE marks" },
  { code: "ciemarks.approve", module: "cie", description: "Approve/lock CIE marks" },

  { code: "exam.view", module: "exam", description: "View examinations" },
  { code: "exam.create", module: "exam", description: "Create examinations" },
  { code: "exam.edit", module: "exam", description: "Edit examinations" },
  { code: "exam.eligibility", module: "exam", description: "Compute exam eligibility" },
  { code: "exam.hallallocation", module: "exam", description: "Allocate exam halls" },

  { code: "result.view", module: "result", description: "View results" },
  { code: "result.create", module: "result", description: "Enter/process marks" },
  { code: "result.approve", module: "result", description: "Approve results" },
  { code: "result.publish", module: "result", description: "Publish results" },
  { code: "results.view", module: "result", description: "View results & grade cards" },
  { code: "results.compute", module: "result", description: "Compute semester results" },
  { code: "results.publish", module: "result", description: "Publish semester results" },
  { code: "results.edit", module: "result", description: "Override result grades" },

  { code: "fees.view", module: "fees", description: "View fee records" },
  { code: "fees.create", module: "fees", description: "Configure fee structures" },
  { code: "fees.collect", module: "fees", description: "Collect payments / issue receipts" },
  { code: "fees.adjust", module: "fees", description: "Apply discounts/waivers" },
  { code: "fees.structure", module: "fees", description: "Manage fee structures" },
  { code: "fees.generate", module: "fees", description: "Generate student fee records" },
  { code: "fees.receive", module: "fees", description: "Record payments and receipts" },

  { code: "notification.send", module: "notification", description: "Send notifications/announcements" },
  { code: "announcement.view", module: "announcement", description: "View announcements" },
  { code: "announcement.create", module: "announcement", description: "Create announcements" },
  { code: "announcement.edit", module: "announcement", description: "Edit/archive announcements" },

  { code: "report.view", module: "report", description: "View institutional reports" },
  { code: "report.export", module: "report", description: "Export reports" },
  { code: "reports.view", module: "report", description: "View reports & analytics" },

  { code: "user.manage", module: "admin", description: "Manage users" },
  { code: "role.manage", module: "admin", description: "Manage roles and permissions" },
  { code: "audit.view", module: "admin", description: "View audit logs" },

  { code: "leave.apply", module: "leave", description: "Apply for leave" },
  { code: "leave.view", module: "leave", description: "View leave requests" },
  { code: "leave.approve", module: "leave", description: "Approve leave requests" },
  { code: "leave.configure", module: "leave", description: "Configure leave types" },

  { code: "staff.attendance.manage", module: "staff", description: "Manage staff attendance" },
];

export type RoleDef = {
  code: string;
  name: string;
  scope: "INSTITUTION" | "DEPARTMENT" | "SELF";
  description?: string;
  permissions: string[];
};

export const ROLES: RoleDef[] = [
  {
    code: "SUPER_ADMIN",
    name: "Super Admin",
    scope: "INSTITUTION",
    description: "Full system control",
    permissions: PERMISSIONS.map((p) => p.code),
  },
  {
    code: "ADMIN",
    name: "Institutional ERP Coordinator",
    scope: "INSTITUTION",
    description: "Operates the complete ERP configuration and institution-wide workflows",
    permissions: PERMISSIONS.map((p) => p.code),
  },
  {
    code: "PRINCIPAL",
    name: "Principal",
    scope: "INSTITUTION",
    description: "Executive institution-wide visibility and drill-down",
    permissions: [
      "dashboard.view",
      "student.view",
      "faculty.view",
      "department.view",
      "academic.view",
      "course.view",
      "attendance.view",
      "timetable.view",
      "assessment.view",
      "questionbank.view",
      "ciemarks.view",
      "exam.view",
      "result.view",
      "results.view",
      "fees.view",
      "report.view",
      "report.export",
      "reports.view",
      "audit.view",
    ],
  },
  {
    code: "MANAGEMENT",
    name: "Management",
    scope: "INSTITUTION",
    description: "Institution-level dashboards and reports",
    permissions: ["dashboard.view", "report.view", "report.export", "result.view", "results.view", "fees.view", "attendance.view", "reports.view"],
  },
  {
    code: "EXAM_CONTROLLER",
    name: "Examination Controller",
    scope: "INSTITUTION",
    description: "Controls the complete examination lifecycle",
    permissions: [
      "dashboard.view",
      "exam.view",
      "exam.create",
      "exam.edit",
      "exam.eligibility",
      "exam.hallallocation",
      "result.view",
      "result.create",
      "result.approve",
      "result.publish",
      "results.view",
      "results.compute",
      "results.publish",
      "results.edit",
      "questionbank.view",
      "questionpaper.approve",
      "ciemarks.view",
      "ciemarks.approve",
      "student.view",
      "course.view",
      "attendance.view",
      "report.view",
      "report.export",
      "reports.view",
      "notification.send",
      "announcement.view",
      "announcement.create",
      "announcement.edit",
    ],
  },
  {
    code: "ACCOUNTS",
    name: "Accounts / Finance",
    scope: "INSTITUTION",
    description: "Fee structures, collections, payments and receipts",
    permissions: [
      "dashboard.view",
      "fees.view",
      "fees.create",
      "fees.collect",
      "fees.adjust",
      "fees.structure",
      "fees.generate",
      "fees.receive",
      "student.view",
      "report.view",
      "report.export",
      "reports.view",
      "notification.send",
      "announcement.view",
      "announcement.create",
      "announcement.edit",
    ],
  },
  {
    code: "PLACEMENT",
    name: "Placement Coordinator",
    scope: "INSTITUTION",
    description: "Placement drives and training",
    permissions: ["dashboard.view", "student.view", "notification.send", "report.view", "reports.view", "announcement.view", "announcement.create", "announcement.edit"],
  },
  {
    code: "SCHOLARSHIP",
    name: "Scholarship Coordinator",
    scope: "INSTITUTION",
    description: "Scholarship opportunities",
    permissions: ["dashboard.view", "student.view", "notification.send", "announcement.view", "announcement.create", "announcement.edit"],
  },
  {
    code: "IQAC",
    name: "IQAC / Accreditation Coordinator",
    scope: "INSTITUTION",
    description: "Accreditation and institutional reporting",
    permissions: ["dashboard.view", "report.view", "report.export", "reports.view", "student.view", "faculty.view", "academic.view"],
  },
  {
    code: "HOD",
    name: "Head of Department",
    scope: "DEPARTMENT",
    description: "Department-wide academic management",
    permissions: [
      "dashboard.view",
      "student.view",
      "student.create",
      "student.edit",
      "faculty.view",
      "academic.view",
      "course.view",
      "course.assign",
      "course.register",
      "attendance.view",
      "attendance.approve",
      "timetable.view",
      "timetable.create",
      "timetable.edit",
      "assessment.view",
      "assessment.create",
      "assessment.edit",
      "assessment.publish",
      "questionbank.view",
      "questionbank.approve",
      "questionpaper.approve",
      "ciemarks.view",
      "ciemarks.approve",
      "exam.view",
      "result.view",
      "results.view",
      "fees.view",
      "report.view",
      "report.export",
      "reports.view",
      "leave.approve",
      "announcement.view",
      "announcement.create",
      "announcement.edit",
      "notification.send",
    ],
  },
  {
    code: "DEPT_COORDINATOR",
    name: "Department ERP Coordinator",
    scope: "DEPARTMENT",
    description: "Operational academic administrator for a department",
    permissions: [
      "dashboard.view",
      "student.view",
      "student.create",
      "student.edit",
      "faculty.view",
      "academic.view",
      "course.view",
      "course.assign",
      "course.register",
      "attendance.view",
      "attendance.approve",
      "timetable.view",
      "timetable.create",
      "timetable.edit",
      "assessment.view",
      "assessment.create",
      "assessment.edit",
      "assessment.publish",
      "questionbank.view",
      "questionbank.approve",
      "questionpaper.approve",
      "ciemarks.view",
      "ciemarks.approve",
      "exam.view",
      "result.view",
      "results.view",
      "fees.view",
      "report.view",
      "reports.view",
      "notification.send",
      "announcement.view",
      "announcement.create",
      "announcement.edit",
    ],
  },
  {
    code: "FACULTY",
    name: "Faculty",
    scope: "SELF",
    description: "Teaching staff managing assigned courses",
    permissions: [
      "dashboard.view",
      "student.view",
      "course.view",
      "attendance.view",
      "attendance.create",
      "attendance.edit",
      "timetable.view",
      "assessment.view",
      "assessment.create",
      "assessment.edit",
      "questionbank.view",
      "questionbank.create",
      "questionbank.edit",
      "questionpaper.create",
      "questionpaper.submit",
      "ciemarks.enter",
      "ciemarks.view",
      "exam.view",
      "result.view",
      "results.view",
      "leave.apply",
      "leave.view",
      "announcement.view",
    ],
  },
  {
    code: "STUDENT",
    name: "Student",
    scope: "SELF",
    description: "Own academic and personal records",
    permissions: [
      "dashboard.view",
      "student.profile.self",
      "attendance.view",
      "timetable.view",
      "ciemarks.view",
"exam.view",
      "result.view",
      "results.view",
      "fees.view",
      "course.view",
      "announcement.view",
    ],
  },
  {
    code: "PARENT",
    name: "Parent / Guardian",
    scope: "SELF",
    description: "Authorized view of linked student",
    permissions: ["dashboard.view", "attendance.view", "ciemarks.view", "result.view", "results.view", "fees.view", "timetable.view", "announcement.view"],
  },
];

export function permissionCodes(): string[] {
  return PERMISSIONS.map((p) => p.code);
}
